name: Render QMD

on:
  schedule:
    - cron: "*/60 * * * *" # every 60 minutes
  workflow_dispatch: # allow manual run

permissions:
  contents: write  # allow pushing changes to the repo

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # --- List files to verify index.qmd exists ---
    - name: List files
      run: ls -R

    # --- Install system libraries ---
    - name: Install system libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libpng-dev \
          libjpeg-dev \
          libcairo2-dev \
          wget \
          gdebi-core \
          git

    # --- Cache Quarto ---
    - name: Cache Quarto
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/quarto
        key: ${{ runner.os }}-quarto-v1.7.34
        restore-keys: |
          ${{ runner.os }}-quarto-

    - name: Install Quarto if missing
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.7.34/quarto-1.7.34-linux-amd64.deb
        sudo gdebi -n quarto-1.7.34-linux-amd64.deb
        rm quarto-1.7.34-linux-amd64.deb

    # --- Setup R ---
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'

    # --- Cache R packages ---
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-packages-${{ hashFiles('**/*.qmd') }}
        restore-keys: |
          ${{ runner.os }}-r-packages-

    # --- Install required R packages ---
    - name: Install required R packages
      run: |
        R -e 'install.packages(c("googlesheets4", "plotly"), repos="https://cloud.r-project.org")'

    # --- Render Quarto document ---
    - name: Render Quarto document
      run: quarto render index.qmd --to html
      # the output will already go to docs/index.html as set in index.qmd

    # --- Commit & push changes to docs/ ---
    - name: Commit and push HTML
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/index.html
        git commit -m "Update rendered HTML [skip ci]" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
