name: Render Quarto Website

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:  # manual trigger

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Install system dependencies
    - name: Install system libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcurl4-openssl-dev \
          libssl-dev \
          libxml2-dev \
          libcairo2-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libpng-dev

    # 3️⃣ Setup R
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'

    # 4️⃣ Setup Quarto
    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    # 5️⃣ Cache R packages
    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-packages-${{ hashFiles('**/*.qmd', '_quarto.yml') }}
        restore-keys: |
          ${{ runner.os }}-r-packages-

    # 6️⃣ Install required R packages
    - name: Install R packages
      run: |
        Rscript -e '
          packages <- c(
            "googlesheets4",
            "dplyr",
            "ggplot2",
            "tidyr",
            "tibble",
            "stringr",
            "forcats",
            "purrr",
            "plotly",
            "htmlwidgets"
          );
          installed <- rownames(installed.packages());
          to_install <- setdiff(packages, installed);
          if(length(to_install) > 0) {
            install.packages(to_install, repos="https://cloud.r-project.org", dependencies=TRUE)
          }
        '

    # 7️⃣ Render Quarto site (outputs to docs/ via _quarto.yml)
    - name: Render Quarto
      run: |
        quarto render .

    # 8️⃣ Deploy docs/ to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

