name: Auto-render Quarto Website

on:
  schedule:
    - cron: "*/60 * * * *"  # every 60 minutes
  workflow_dispatch:        # allows manual trigger

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ${{ github.workspace }}/.R/library

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      # 3️⃣ Setup Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 4️⃣ Cache R packages
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-packages-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-packages-

      # 5️⃣ Install R dependencies from DESCRIPTION
      - name: Install R dependencies
        run: |
          # create library folder if it doesn't exist
          dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE, showWarnings = FALSE)
          
          # install remotes if missing
          if (!requireNamespace("remotes", quietly = TRUE)) {
            install.packages("remotes", lib = Sys.getenv("R_LIBS_USER"))
          }
          
          # install all packages from DESCRIPTION
          Rscript -e 'remotes::install_deps(dependencies = TRUE, lib = Sys.getenv("R_LIBS_USER"))'

      # 6️⃣ Render Quarto website
      - name: Render Quarto website
        run: quarto render

      # 7️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

