name: Auto-render Quarto Website

on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ${{ github.workspace }}/.R/library

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install minimal system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            pkg-config

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-packages-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-packages-

      - name: Install remotes if missing
        run: Rscript -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes", lib = Sys.getenv("R_LIBS_USER"))'

      - name: Install R dependencies from DESCRIPTION with binary fallback
        run: |
          Rscript -e '
          options(pkgType = "binary")  # try binaries first
          pkgs <- tryCatch(
            remotes::install_deps(dependencies = TRUE, lib = Sys.getenv("R_LIBS_USER")),
            error = function(e) {
              message("Binary install failed, falling back to source...")
              options(pkgType = "source")
              remotes::install_deps(dependencies = TRUE, lib = Sys.getenv("R_LIBS_USER"))
            }
          )
          '

      - name: Render Quarto website
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
